### ISSUE TITLE
Display of visualized graphs in the paper

### ISSUE THREAD

**Issue by lvhuanhuan123** [LTTM/IL-SemSegm#2]
Hello, I would like to ask how the visualized graph in your paper is displayed?

First question. Can only show 5 new classes of segmentation graphs?  Can the 15 classes of segmentation maps  the model learned earlier be displayed?
Second question. Which code is the specific result of the 20 classes of segmentation in the article? Did you change 19 to 20 directly? How to save the segmentation map at this time?

Looking forward to your reply. Thank you.

**Comment by umbertomichieli** [comment]
Hello,

First, please have a look at [this paper](https://arxiv.org/pdf/1911.03462.pdf), which extends the conference paper and shows many additional results. Of course, many other setups are possible.
In particular, Figure 4 and 5 should answer your questions. 
Yes, it is possible to show the segmentation maps of every trained model (see below for the procedure to achieve it)

Regarding you second question: the baseline model is simply run using the default learning parameters and all the classes are learned during the first step. 
To save the segmentation map, you need to export the trained model (via export_graph.py, which save a .pb file) and then to perform inference (via inference.py). 

I hope this clarifies your doubts.
Umberto

**Comment by lvhuanhuan123** [comment]
Thank you very much for your reply. I will try again.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 晚上6:09
收件人: "LTTM/IL-SemSegm"<IL-SemSegm@noreply.github.com&gt;; 
抄送: "NMS"<3052827633@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [LTTM/IL-SemSegm] Display of visualized graphs in the paper (#2)





 
Hello,
 
First, please have a look at this paper, which extends the conference paper and shows many additional results. Of course, many other setups are possible.
 In particular, Figure 4 and 5 should answer your questions.
 Yes, it is possible to show the segmentation maps of every trained model (see below for the procedure to achieve it)
 
Regarding you second question: the baseline model is simply run using the default learning parameters and all the classes are learned during the first step.
 To save the segmentation map, you need to export the trained model (via export_graph.py, which save a .pb file) and then to perform inference (via inference.py).
 
I hope this clarifies your doubts.
 Umberto
