### ISSUE TITLE
Bug in LD1

### ISSUE THREAD

**Issue by ponpon010548** [LTTM/IL-SemSegm#3]
Hi! I have tested for LD1 recently. I found two errors and had corrected it.
1. **line 35 in script.job** 
`--validation_file ../../../sample_dataset/tfrecords/train_20.tfrecords`
should be
`--validation_file ../../sample_dataset/tfrecords/train_20.tfrecords`

2. UnboundLocalError: local variable 'G_final_loss_value' referenced before assignment in **train_with_distillation.py**
There is the same bug as in issue#1. But I didn't find the answer to that problem. 
Here, I solved it by **adding `G_final_loss_value = 0` in line 171**

FYI, thanks!

**Comment by umbertomichieli** [comment]
Hi, thank you for your message. 

1) I corrected the wrong path.

2) I think that you should not encounter that error if your training is going smoothly.

Kind regards,
Umberto

**Comment by ponpon010548** [comment]
Thank you for your response, I tried to rerun LD1 and there was no error message!
Now, I can try LD2!
Thanks!
